namespace MiniRealms.Levels.Tiles
{
    public enum TileId
    {
        Grass,
        Rock,
        Water,
        Flower,
        Tree,
        Dirt,
        Sand,
        Cactus,
        Hole,
        TreeSapling,
        CactusSapling,
        Farmland,
        Wheat,
        Lava,
        StairsDown,
        StairsUp,
        InfiniteFall,
        Cloud,
        Hardrock,
        IronOre,
        GoldOre,
        GemOre,
        CloudCactus,
        RedFlower,
        YellowFlower
    }
}